### ISSUE TITLE
undefined method `load_paths=' for ActiveSupport::Dependencies:Module

### ISSUE THREAD

**Issue by cadmium-zz** [maccman/supermodel#3]
Howdy maccman,

I just tried to get the helloworld app working (in the last 4 hours) on Ubuntu 10.04 (just after upgrading SuperModel to 0.1.4).  I'm running Ruby 1.9.1.
bowline-gen app helloworld: worked fine (thanks for fixing supermodel!)
cd helloworld
bowline-bundle: this worked OK and put the gems in the vendor/gems directory
./script/run produces the following error:

<pre>
Setting up Bowline. This could take a while...
/home/cadmium/ruby/bowline/helloworld/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/initializer.rb:113:in `set_autoload_paths': undefined method `load_paths=' for ActiveSupport::Dependencies:Module (NoMethodError)
    from /home/cadmium/ruby/bowline/helloworld/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/initializer.rb:335:in `process'
    from /home/cadmium/ruby/bowline/helloworld/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/initializer.rb:71:in `run'
    from /home/cadmium/ruby/bowline/helloworld/config/environment.rb:4:in `<top (required)>'
    from /home/cadmium/ruby/bowline/helloworld/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:219:in `require'
    from /home/cadmium/ruby/bowline/helloworld/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:219:in `block in require'
    from /home/cadmium/ruby/bowline/helloworld/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:205:in `block in load_dependency'
    from /home/cadmium/ruby/bowline/helloworld/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:570:in `new_constants_in'
    from /home/cadmium/ruby/bowline/helloworld/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:205:in `load_dependency'
    from /home/cadmium/ruby/bowline/helloworld/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:219:in `require'
    from /home/cadmium/ruby/bowline/helloworld/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/tasks/misc.rake:2:in `block in <top (required)>'
    from /var/lib/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:636:in `call'
    from /var/lib/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:636:in `block in execute'
    from /var/lib/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:631:in `each'
    from /var/lib/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
    from /var/lib/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:597:in `block in invoke_with_call_chain'
    from /usr/lib/ruby/1.9.1/monitor.rb:190:in `mon_synchronize'
    from /var/lib/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
    from /var/lib/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:607:in `block in invoke_prerequisites'
    from /var/lib/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:604:in `each'
    from /var/lib/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:604:in `invoke_prerequisites'
    from /var/lib/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:596:in `block in invoke_with_call_chain'
    from /usr/lib/ruby/1.9.1/monitor.rb:190:in `mon_synchronize'
    from /var/lib/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
    from /var/lib/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
    from /home/cadmium/ruby/bowline/helloworld/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/commands/run.rb:4:in `<top (required)>'
    from /home/cadmium/ruby/bowline/helloworld/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:219:in `require'
    from /home/cadmium/ruby/bowline/helloworld/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:219:in `block in require'
    from /home/cadmium/ruby/bowline/helloworld/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:205:in `block in load_dependency'
    from /home/cadmium/ruby/bowline/helloworld/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:570:in `new_constants_in'
    from /home/cadmium/ruby/bowline/helloworld/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:205:in `load_dependency'
    from /home/cadmium/ruby/bowline/helloworld/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:219:in `require'
    from ./script/run:3:in `<main>'
</pre>

By the way, here is my gem list:

<pre>
*** LOCAL GEMS ***

actionmailer (2.3.8)
actionpack (2.3.8)
activemodel (3.0.0.rc)
activerecord (2.3.8)
activeresource (2.3.8)
activesupport (3.0.0.rc, 2.3.8)
bowline (0.9.3)
bowline-bundler (0.0.4)
builder (2.1.2)
diff-lcs (1.1.2)
extlib (0.9.15)
highline (1.6.1)
i18n (0.4.1)
mechanize (1.0.0)
nokogiri (1.4.3.1)
rack (1.2.1, 1.1.0)
rails (2.3.8)
rake (0.8.7)
redcar (0.3.8.4)
rubyzip (0.9.4)
rubyzip2 (2.0.1)
supermodel (0.1.4)
templater (1.0.0)
</pre>

I can't wait to try this out so hopefully these bugs can be sorted out quickly (if it isn't something wrong that I did).
Thanks,
cadmium

**Comment by maccman** [comment]
Try using github master of Bowline and ActiveSupport 3 RC1

**Comment by cadmium-zz** [comment]
Thanks for your quick reply maccman.  I'm not sure how to do the things you listed, so instead I'll wait until the gems are updated.
Also sorry for putting this issue in supermodel and not bowline (it was late at night, I was tired, etc..:)
Thanks,
cadmium

**Comment by datnt** [comment]
Hi maccman,

I also faced the same problem.
Is there any wayout.

If there is anything I can help, please let me know.

Thank you,
Dat
